const tableMockData = [
  { id: 1, name: "John Doe", age: 30, city: "New York" },
  { id: 2, name: "Jane Smith", age: 25, city: "Los Angeles" },
  { id: 3, name: "Bob Johnson", age: 35, city: "Chicago" },
  { id: 4, name: "Alice Brown", age: 28, city: "Houston" },
  { id: 5, name: "Charlie Davis", age: 32, city: "Phoenix" },
  { id: 6, name: "Eve Evans", age: 29, city: "Philadelphia" },
  { id: 7, name: "Frank Green", age: 40, city: "San Antonio" },
  { id: 8, name: "Grace Harris", age: 27, city: "San Diego" },
  { id: 9, name: "Hank Hill", age: 33, city: "Dallas" },
  { id: 10, name: "Ivy Jackson", age: 26, city: "San Jose" },
  { id: 11, name: "Jack King", age: 31, city: "Austin" },
  { id: 12, name: "Karen Lee", age: 34, city: "Jacksonville" },
  { id: 13, name: "Leo Martinez", age: 29, city: "Fort Worth" },
  { id: 14, name: "Mia Nelson", age: 28, city: "Columbus" },
  { id: 15, name: "Nina Owens", age: 35, city: "Charlotte" },
  { id: 16, name: "Oscar Perez", age: 30, city: "San Francisco" },
  { id: 17, name: "Paul Quinn", age: 32, city: "Indianapolis" },
  { id: 18, name: "Quincy Roberts", age: 27, city: "Seattle" },
  { id: 19, name: "Rachel Scott", age: 33, city: "Denver" },
  { id: 20, name: "Sam Taylor", age: 26, city: "Washington" },
  { id: 21, name: "Tina Underwood", age: 31, city: "Boston" },
  { id: 22, name: "Uma Vance", age: 34, city: "El Paso" },
  { id: 23, name: "Victor White", age: 29, city: "Nashville" },
  { id: 24, name: "Wendy Xiong", age: 28, city: "Detroit" },
  { id: 25, name: "Xander Young", age: 35, city: "Oklahoma City" },
  { id: 26, name: "Yara Zane", age: 30, city: "Las Vegas" },
  { id: 27, name: "Zane Adams", age: 32, city: "Memphis" },
  { id: 28, name: "Amy Baker", age: 27, city: "Louisville" },
  { id: 29, name: "Brian Clark", age: 33, city: "Baltimore" },
  { id: 30, name: "Cathy Diaz", age: 26, city: "Milwaukee" },
];

export { tableMockData };
